default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: GENERAL_DB
  port: '3306'

production:
  <<: *default
  database: GENERAL_DB
  username: admin
  password: <%= ENV['LOG_API_DATABASE_PASSWORD'] %>
  host: 160.153.128.6
